name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, "absensigudang-runner"]

    steps:
      - name: Run Deployment Script
        run: |
          cd /srv/docker/absensigudang
          bash ./deploy.sh
