name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Git Pull di Folder Production
        run: |
          cd /srv/docker/absensi
          echo "Menarik kode terbaru (git pull) di server..."
          git fetch --all
          git reset --hard origin/main
          git clean -fd
          git pull origin main

      - name: Build & Install di Host Server
        run: |
          echo "Instalasi dependensi backend..."
          cd /srv/docker/absensi/backend
          npm install
          
          echo "Instalasi dependensi dan compile frontend..."
          cd /srv/docker/absensi/frontend
          npm install
          npm run build
          
          echo "✅ Deployment CI/CD (Git Pull Mode) BERHASIL 100%!"
